# -*- coding=utf-8 -*-
import time
def a1():
	print '\033[1;33;1m';

	print "\n\r";
	print " =**#%*#*+*****=.";
	time.sleep(0.1); 
	print " :**###*#*********+.. .";
	time.sleep(0.1);
	print "=##%#= ****+*##**********";
	time.sleep(0.1);
	print "#**+::%***  .************=";
	time.sleep(0.1);
	print " @%%%#**** *#*+****#*****.";
	time.sleep(0.1);
	print ":@@@@@*****=*******#*****";
	time.sleep(0.1);
	print "=*#%#++**+**************=";
	time.sleep(0.1);
	print " ..=##**#%#*********:***.";
	time.sleep(0.1);
	print "   .#%%##*+*******+  .*%";
	time.sleep(0.1);
	print "    #***+#++****#.";
	time.sleep(0.1);
	print "     .::::.:******=              +*+: .";
	time.sleep(0.1);
	print "        =:.*********:            :******=.";
	time.sleep(0.1);
	print "       *.:=***********=            +******+#";
	time.sleep(0.1);
	print "      =*..+*************=           .*******.";
	time.sleep(0.1);
	print "      **.::***************+.          +******";
	time.sleep(0.1);
	print "      ***..+*****************.         #*****=";
	time.sleep(0.1);
	print "      +**+.:*****#+************        +*****+:";
	time.sleep(0.1);
	print "      =****=********************=      +*****=";
	time.sleep(0.1);
	print "      :****#*****%+**************:    :*****#.";
	time.sleep(0.1);
	print "      :***************************=.:+******";
	time.sleep(0.1);
	print "      :*********=.+***************#******+=";
	time.sleep(0.1);
	print "    ..****#***+#+*++***************==:.";
	time.sleep(0.1);
	print "   #****#*****#**+*****#*#*******:";
	time.sleep(0.1);
	print "   =+**#*******.=#*************#";
	time.sleep(0.1);
	print "        .:=+=.   .=+***+++==::::";
	print '\033[0m';


def a2():
	print '\033[1;33;1m';
	print "\n\r";
	print "                       @@@";
	time.sleep(0.1); 
	print "            @@@        @@@@";
	time.sleep(0.1);
	print "            @@@@     @@@@@@";
	time.sleep(0.1);
	print "           @@@@@@   @@@@@@@";
	time.sleep(0.1);
	print "           @@@@@@@  @@@@@@@";
	time.sleep(0.1);
	print "           @@@@@@@@@@@@@@@@";
	time.sleep(0.1);
	print "      @@@@@@@@@@@@@@@@@@@@@";
	time.sleep(0.1);
	print "       @@@@@@@@@      @@@@@";
	time.sleep(0.1);
	print "        @@@@@         @@@@";
	time.sleep(0.1);
	print "               @ @  @ @@@@";
	time.sleep(0.1);
	print "                   @@@@@@        @@";
	time.sleep(0.1);
	print "              @    @ @@@@       @@";
	time.sleep(0.1);
	print "               @ @   @@@       @@@";
	time.sleep(0.1);
	print "             @@@@@@@@@@@@  @@@@@@@";
	time.sleep(0.1);
	print "               @@@@@@@@@@@@@@@@@@@";
	time.sleep(0.1);
	print "                @@@@@@@@@@@@@@@@@@@";
	time.sleep(0.1);
	print "                 @@@@@@@@@@@@@@@@@@";
	time.sleep(0.1);
	print "                 @@@@@@@@@@@@@@@@@";
	time.sleep(0.1);
	print "      @@@@@@@@     @  @@   @@  @@";
	time.sleep(0.1);
	print "     @@@@@@@@@@   @@@ @@@  @@  @@@";
	time.sleep(0.1);
	print "             @@@@@@@@@@@@@@@@@@";
	print '\033[0m';

def a3():
	print '\033[1;33;1m';
	print "\n\r";
	print "              *@@@      *@@@@";
	time.sleep(0.1); 
	print "            .@@*.@.    .@@ *@@.";
	time.sleep(0.1);
	print "            .    @@    @@    .@";
	time.sleep(0.1);
	print "                 .@***@@";
	time.sleep(0.1);
	print "              ..@*.****@*.";
	time.sleep(0.1);
	print "              @***********@      .**.";
	time.sleep(0.1);
	print "         ...*.***.**.****@@     . .*@@";
	time.sleep(0.1);
	print "       **   .@***@@@*.*  @*@         @@";
	time.sleep(0.1);
	print "     .@.      @@@@@***@@@*.*.....   .@";
	time.sleep(0.1);
	print "    @  ...    .@@@@@@.        @****@@";
	time.sleep(0.1);
	print "     @*        ***.   ...  **. @****@*";
	time.sleep(0.1);
	print "    @ .@*      *          ***  @*******";
	time.sleep(0.1);
	print "   @** . *@*.         ..** *@ .@******@";
	time.sleep(0.1);
	print "    .@..  . .***...**.  .. ** @******.**";
	time.sleep(0.1);
	print "      @@* . .  .   . . . .@. @*******..**";
	time.sleep(0.1);
	print "    *@*@@@**.   .    **....*@******@**..@";
	time.sleep(0.1);
	print "   @****@@@@**@**********@@**@@@*@@.****@";
	time.sleep(0.1);
	print "  @****@  .*@@***********@@*****@   @****";
	time.sleep(0.1);
	print " @****@      *@@@@@@@@***..@**...@  @**@....";
	time.sleep(0.1);
	print " @****@***.  @@*****@@     *****.@ .@****@*@@.";
	time.sleep(0.1);
	print " @*****@**@@. ..*.**.  *@@@******@ .@****@*@**";
	time.sleep(0.1);
	print " @******@*@@@         @*@**@*****@   .***....";
	time.sleep(0.1);
	print " .*@@@@@@**.          @@**@******@";
	time.sleep(0.1);
	print "                        ...*****.";
	print '\033[0m';


def a4():
	print '\033[1;33;1m';
	print "\n\r";
	print "     :=o+++i+++++o+~                                       .;:";
	time.sleep(0.1); 
	print "    Io+++i+oi++++i+o                                        I..";
	time.sleep(0.1);
	print "    ;++i++i+oi++++iOo;                                      i.:";
	time.sleep(0.1);
	print "    ~ooE=+++oii+++ioi+o:                                    +i;";
	time.sleep(0.1);
	print "  .;.O++++++O+++iiOi+++++`                                 `o;;";
	time.sleep(0.1);
	print "I:.  ~I;;== `=ooooi+++i++oo++ii===I:~.                     oo;.";
	time.sleep(0.1);
	print "O ```            .++++++++++++++++++++oo+iI;;:~``        :o+O.";
	time.sleep(0.1);
	print "I`   `  :I:~:~ ``  =++++++++++++++++++i++++++++oooooO+;IoOi:";
	time.sleep(0.1);
	print " ~::~~=I;.   .; ````O+++++++++++++++++++++++++++++i+i++O~";
	time.sleep(0.1);
	print "               :.`` `I+++++++++++++++++++++++i++++++++++i";
	time.sleep(0.1);
	print "                I ``` i+++++++++++++++++++++ooo+++++++ii+I";
	time.sleep(0.1);
	print "                ; ``` 8ii++++++++++++++i+o=:  `=o+++++++oO";
	time.sleep(0.1);
	print "                : ``` I++++++iii+++++++o~   ``   oo+++o; =";
	time.sleep(0.1);
	print "                :~ `` .O+oiiiOi+++++o+i~     .~.` .;;~   :.";
	time.sleep(0.1);
	print "                 :: ``   ~oooII:;II:    .::::. ; ``   ``` I";
	time.sleep(0.1);
	print "                  .= ` :i      I...~~~..I`   ` I ``````````;~";
	time.sleep(0.1);
	print "                   ~~``~.I `` ~.         :~ `  ;~  ```````` I";
	time.sleep(0.1);
	print "                    + ` I.~ ` ~.           ~~:: `::  `  ``` I";
	time.sleep(0.1);
	print "                    ~~` : I ``.~               :.  i~~:;``` ~~";
	time.sleep(0.1);
	print "                     = ` ;..`` ;                I  I    ;. ` ;`";
	time.sleep(0.1);
	print "                     I  `I ;`` I                ;.` ;    :.`` =";
	time.sleep(0.1);
	print "                 `~~:. .:  `: ``;             `:~ `;`     = ``;";
	time.sleep(0.1);
	print "               `I;`   .;  `; ` I           `;:.`  =    `.;`  i";
	time.sleep(0.1);
	print " :`~.  ``````  ::;~~~:.;I::```I . ~`` :`.`~;i:=~~; ``:=.;.:~I`";
	time.sleep(0.1);
	print " :..` .`..```      ..`;;=:=;~~~ . .```~`` ~`.~`...`..~=:I:I;:`";
	print '\033[0m';
